CRITICAL - 2022-03-11 02:15:01 --> Trying to access array offset on value of type null
#0 C:\xampp\htdocs\gplan\app\Controllers\Users.php(469): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Trying to acces...', 'C:\\xampp\\htdocs...', 469, Array)
#1 C:\xampp\htdocs\gplan\system\CodeIgniter.php(914): App\Controllers\Users->dashboard('1')
#2 C:\xampp\htdocs\gplan\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\gplan\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\gplan\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-03-11 12:49:07 --> Cannot redeclare App\Controllers\Wallet::transaction()
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-11 12:49:07 --> Cannot redeclare App\Controllers\Wallet::transaction()
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2022-03-11 12:49:07 --> Cannot redeclare App\Controllers\Wallet::transaction()
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
<<<<<<< HEAD
CRITICAL - 2022-03-11 13:04:06 --> Access denied for user '****'@'localhost' (using ****: YES)
#0 D:\xampp\gplan\system\Database\BaseConnection.php(377): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\gplan\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\gplan\system\Database\BaseBuilder.php(1845): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 D:\xampp\gplan\app\Models\WalletWithdrawModel.php(127): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\gplan\app\Core\BaseController.php(76): App\Models\WalletWithdrawModel->getCountOfUndone()
#5 D:\xampp\gplan\system\CodeIgniter.php(887): App\Core\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 D:\xampp\gplan\system\CodeIgniter.php(395): CodeIgniter\CodeIgniter->createController()
#7 D:\xampp\gplan\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\gplan\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-03-11 13:04:06 --> Access denied for user '****'@'localhost' (using ****: YES)
#0 D:\xampp\gplan\system\Database\BaseConnection.php(377): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\gplan\system\Database\BaseConnection.php(643): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\gplan\system\Database\BaseBuilder.php(1845): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 D:\xampp\gplan\app\Models\WalletWithdrawModel.php(127): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\gplan\app\Core\BaseController.php(76): App\Models\WalletWithdrawModel->getCountOfUndone()
#5 D:\xampp\gplan\system\CodeIgniter.php(887): App\Core\BaseController->initController(Object(CodeIgniter\HTTP\IncomingRequest), Object(CodeIgniter\HTTP\Response), Object(CodeIgniter\Log\Logger))
#6 D:\xampp\gplan\system\CodeIgniter.php(395): CodeIgniter\CodeIgniter->createController()
#7 D:\xampp\gplan\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 D:\xampp\gplan\index.php(45): CodeIgniter\CodeIgniter->run()
#9 {main}
=======
CRITICAL - 2022-03-11 13:49:12 --> Undefined variable: error
#0 C:\xampp\htdocs\gplan\app\Controllers\Users.php(292): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 292, Array)
#1 C:\xampp\htdocs\gplan\system\CodeIgniter.php(914): App\Controllers\Users->submit_receipt()
#2 C:\xampp\htdocs\gplan\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\gplan\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\gplan\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-03-11 13:49:19 --> Undefined variable: error
#0 C:\xampp\htdocs\gplan\app\Controllers\Users.php(292): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 292, Array)
#1 C:\xampp\htdocs\gplan\system\CodeIgniter.php(914): App\Controllers\Users->submit_receipt()
#2 C:\xampp\htdocs\gplan\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\gplan\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\gplan\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-03-11 13:49:19 --> Undefined variable: error
#0 C:\xampp\htdocs\gplan\app\Controllers\Users.php(292): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 292, Array)
#1 C:\xampp\htdocs\gplan\system\CodeIgniter.php(914): App\Controllers\Users->submit_receipt()
#2 C:\xampp\htdocs\gplan\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\gplan\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\gplan\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-03-11 15:09:51 --> Undefined variable: family
#0 C:\xampp\htdocs\gplan\app\Controllers\Users.php(823): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 823, Array)
#1 C:\xampp\htdocs\gplan\system\CodeIgniter.php(914): App\Controllers\Users->family_tree('1')
#2 C:\xampp\htdocs\gplan\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\gplan\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\gplan\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-03-11 15:09:51 --> Undefined variable: family
#0 C:\xampp\htdocs\gplan\app\Controllers\Users.php(823): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 823, Array)
#1 C:\xampp\htdocs\gplan\system\CodeIgniter.php(914): App\Controllers\Users->family_tree('1')
#2 C:\xampp\htdocs\gplan\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\gplan\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\gplan\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-03-11 15:09:51 --> Undefined variable: family
#0 C:\xampp\htdocs\gplan\app\Controllers\Users.php(823): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 823, Array)
#1 C:\xampp\htdocs\gplan\system\CodeIgniter.php(914): App\Controllers\Users->family_tree('1')
#2 C:\xampp\htdocs\gplan\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\gplan\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\gplan\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-03-11 15:11:13 --> Undefined variable: level
#0 C:\xampp\htdocs\gplan\app\Controllers\Users.php(551): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 551, Array)
#1 C:\xampp\htdocs\gplan\system\CodeIgniter.php(914): App\Controllers\Users->dashboard('1')
#2 C:\xampp\htdocs\gplan\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\gplan\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\gplan\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-03-11 15:11:13 --> Undefined variable: level
#0 C:\xampp\htdocs\gplan\app\Controllers\Users.php(551): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 551, Array)
#1 C:\xampp\htdocs\gplan\system\CodeIgniter.php(914): App\Controllers\Users->dashboard('1')
#2 C:\xampp\htdocs\gplan\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\gplan\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\gplan\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-03-11 15:11:13 --> Undefined variable: level
#0 C:\xampp\htdocs\gplan\app\Controllers\Users.php(551): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 551, Array)
#1 C:\xampp\htdocs\gplan\system\CodeIgniter.php(914): App\Controllers\Users->dashboard('1')
#2 C:\xampp\htdocs\gplan\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#3 C:\xampp\htdocs\gplan\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 C:\xampp\htdocs\gplan\index.php(45): CodeIgniter\CodeIgniter->run()
#5 {main}
CRITICAL - 2022-03-11 15:14:01 --> Undefined variable: i
#0 C:\xampp\htdocs\gplan\app\Views\admin\users\family_tree.php(119): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 119, Array)
#1 C:\xampp\htdocs\gplan\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\gplan\system\Common.php(1087): CodeIgniter\View\View->render('admin/users/fam...', Array, true)
#3 C:\xampp\htdocs\gplan\app\Controllers\Users.php(827): view('admin/users/fam...')
#4 C:\xampp\htdocs\gplan\system\CodeIgniter.php(914): App\Controllers\Users->family_tree('1')
#5 C:\xampp\htdocs\gplan\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\gplan\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\gplan\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-03-11 15:14:02 --> Undefined variable: i
#0 C:\xampp\htdocs\gplan\app\Views\admin\users\family_tree.php(119): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\xampp\\htdocs...', 119, Array)
#1 C:\xampp\htdocs\gplan\system\View\View.php(246): include('C:\\xampp\\htdocs...')
#2 C:\xampp\htdocs\gplan\system\Common.php(1087): CodeIgniter\View\View->render('admin/users/fam...', Array, true)
#3 C:\xampp\htdocs\gplan\app\Controllers\Users.php(827): view('admin/users/fam...')
#4 C:\xampp\htdocs\gplan\system\CodeIgniter.php(914): App\Controllers\Users->family_tree('1')
#5 C:\xampp\htdocs\gplan\system\CodeIgniter.php(400): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Users))
#6 C:\xampp\htdocs\gplan\system\CodeIgniter.php(308): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\gplan\index.php(45): CodeIgniter\CodeIgniter->run()
#8 {main}
>>>>>>> bc56a85a4003302df1d49eff6f70bbc29b74b98e
